In [1]:
import numpy as np
import networkx as nx
import matplotlib.pyplot as plt
import copy
from uniform_attachment_model  import matrix_uniform_attachment
from tqdm.notebook import tqdm
import pandas as pd
import time
import copy
import  heapq

/home/adsayan/.local/lib/python3.10/site-packages/matplotlib/projections/__init__.py:63: UserWarning: Unable to import Axes3D. This may be due to multiple versions of Matplotlib being installed (e.g. as a system package and as a pip package). As a result, the 3D projection is not available.
  warnings.warn("Unable to import Axes3D. This may be due to multiple versions of "


0.07219767570495605


In [23]:
matrix = []
row = [0] * 300
for i in range(300):
    matrix.append(row)

In [24]:
for i, row in enumerate(matrix):
    for j, column in enumerate(row):
        matrix[i][j] = np.random.random()

In [25]:
matrix = np.array(matrix)

In [40]:
matrix = np.array([[3,2,2], [2,3,-2]])

In [41]:
U, S, Vh = np.linalg.svd(matrix)


In [42]:
n = matrix.shape[0]

In [43]:
p_hat = 1  
threshold = 2.02 * np.sqrt(n * p_hat)

In [44]:
S_indices = np.where(S >= threshold)[0]

In [45]:
S_indices

array([0, 1])

In [46]:
W = sum(S[i] * np.outer(U[:, i], Vh[i, :]) for i in S_indices)

In [47]:
W

array([[ 3.,  2.,  2.],
       [ 2.,  3., -2.]])

In [57]:
def transform_w_to_m_hat(W):
    M_hat = np.where(W > 1, 1, np.where(W < -1, -1, W))
    return M_hat

In [58]:
M_hat = transform_w_to_m_hat(W)

In [59]:
M_hat

array([[ 1.,  1.,  1.],
       [ 1.,  1., -1.]])

In [2]:
def transform_w_to_m_hat(W):
    return np.where(W > 1, 1, np.where(W < -1, -1, W))

In [11]:
def matrix_b(m, variance_k=False):
    matrix = copy.deepcopy(m)

    M_max = np.max(np.abs(matrix))
    if M_max != 0:
        matrix = matrix / M_max

    U, S, Vh = np.linalg.svd(matrix, full_matrices=False)

    n = matrix.shape[0]
    p_hat = 1 


    
    if variance_k:
        sigma_squared = np.var(matrix)  
        q_hat = p_hat * sigma_squared + p_hat * (1 - p_hat) * (1 - sigma_squared)
        threshold = 2.02 * np.sqrt(n * q_hat)
        
    else:
        threshold = 2.02 * np.sqrt(n * p_hat)


    S_indices = np.where(S >= threshold)[0]

    
    W = sum(S[i] * np.outer(U[:, i], Vh[i, :]) for i in S_indices)
    matrix = transform_w_to_m_hat(W)

    return matrix

In [12]:
matrix = np.array([[3,2,2], [2,3,-2]])

In [13]:
k = matrix_b(matrix)

In [14]:
k

array(0)